// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dHGS3InufaTrJCftdCAK3uSxVUvRHD0',
    appId: '1:907918136688:web:f7e7fe5277fbfc3c596bb5',
    messagingSenderId: '907918136688',
    projectId: 'lecapase-booking-3af33',
    authDomain: 'lecapase-booking-3af33.firebaseapp.com',
    storageBucket: 'lecapase-booking-3af33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvA62duQQt-ewklYVsu9A6xrg-fbkHzbs',
    appId: '1:907918136688:android:933dac528de5cd9e596bb5',
    messagingSenderId: '907918136688',
    projectId: 'lecapase-booking-3af33',
    storageBucket: 'lecapase-booking-3af33.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8dHGS3InufaTrJCftdCAK3uSxVUvRHD0',
    appId: '1:907918136688:web:c10eb8fa01f2bfdc596bb5',
    messagingSenderId: '907918136688',
    projectId: 'lecapase-booking-3af33',
    authDomain: 'lecapase-booking-3af33.firebaseapp.com',
    storageBucket: 'lecapase-booking-3af33.firebasestorage.app',
  );
}
